# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nNPjAW7RVGUnV-RXaucJNp619yl1jrbv
"""

!pip install gradio transformers torch

import gradio as gr
from transformers import pipeline

# Initialize the huggingface pipeline
classifier = pipeline("sentiment-analysis")

def analysis_sentimental(text):
    # 1. Handle Empty input
    if not text or not text.strip():
        return "Empty Input", "0.00%"

    # 2. Analyze multiple sentences (Allow users to enter several sentences, one per line)
    sentences = [line.strip() for line in text.split('\n') if line.strip()]

    labels = []
    scores = []

    for sentence in sentences:
        result = classifier(sentence)[0]

        # Format the label
        labels.append(f"{sentence} -> {result['label']}")

        # 3. Format score up to two decimal places as a percentage
        score_pct = result['score'] * 100
        scores.append(f"{sentence} -> {score_pct:.2f}%")

    return "\n".join(labels), "\n".join(scores)

# Create the Gradio App
app = gr.Interface(
    fn=analysis_sentimental,
    # 4. Make the input box larger (lines=5)
    inputs=gr.Textbox(
        lines=5,
        placeholder="Enter sentences here (one per line)...",
        label="Input Text"
    ),
    # 5. Display both label and score separately
    outputs=[
        gr.Textbox(label="Sentiment Label"),
        gr.Textbox(label="Confidence Score")
    ],
    # 6. Add a title to the app
    title="Sentiment Analysis App",
    # 7. Add ready-made example sentences
    examples=[
        ["I am absolutely thrilled with this new update!"],
        ["I'm really frustrated that my delivery is late."],
        ["The food was okay, nothing special.\nHowever, the dessert was fantastic!"]
    ]
)

# Launch the app for Render
if __name__ == "__main__":
    app.launch(server_name="0.0.0.0", server_port=10000)