# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nNPjAW7RVGUnV-RXaucJNp619yl1jrbv
"""



import gradio as gr
import os
from textblob import TextBlob

def analysis_sentimental(text):
    if not text or not text.strip():
        return "Empty Input", "0.00%"
    
    sentences = [line.strip() for line in text.split('\n') if line.strip()]
    labels = []
    scores = []
    
    for sentence in sentences:
        try:
            # Run the local TextBlob AI
            blob = TextBlob(sentence)
            polarity = blob.sentiment.polarity
            
            # TextBlob gives a score from -1.0 (Negative) to 1.0 (Positive)
            if polarity > 0:
                label = "POSITIVE"
            elif polarity < 0:
                label = "NEGATIVE"
            else:
                label = "NEUTRAL"
                
            # Convert the score into a clean percentage
            score_pct = abs(polarity) * 100
            
            labels.append(f"{sentence} -> {label}")
            scores.append(f"{sentence} -> {score_pct:.2f}%")
            
        except Exception as e:
            labels.append(f"{sentence} -> Error")
            scores.append(f"{sentence} -> 0.00%")
            
    return "\n".join(labels), "\n".join(scores)

# Create the Gradio App
app = gr.Interface(
    fn=analysis_sentimental,
    inputs=gr.Textbox(
        lines=5, 
        placeholder="Enter sentences here (one per line)...", 
        label="Input Text"
    ),
    outputs=[
        gr.Textbox(label="Sentiment Label"), 
        gr.Textbox(label="Confidence Score")
    ],
    title="Sentiment Analysis App",
    examples=[
        ["I am absolutely thrilled with this new update!"],
        ["I'm really frustrated that my delivery is late."],
        ["The food was okay, nothing special.\nHowever, the dessert was fantastic!"]
    ]
)

# Launch the app for Render
if __name__ == "__main__":
    app.launch(server_name="0.0.0.0", server_port=int(os.environ.get('PORT', 7860)))
