# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nNPjAW7RVGUnV-RXaucJNp619yl1jrbv
"""



 import gradio as gr
import os
import requests

# Point to Hugging Face's free serverless API
API_URL = "https://api-inference.huggingface.co/models/distilbert-base-uncased-finetuned-sst-2-english"

def analysis_sentimental(text):
    if not text or not text.strip():
        return "Empty Input", "0.00%"
    
    sentences = [line.strip() for line in text.split('\n') if line.strip()]
    labels = []
    scores = []
    
    for sentence in sentences:
        try:
            # Ask the Hugging Face server to analyze the text
            response = requests.post(API_URL, json={"inputs": sentence})
            data = response.json()
            
            # Extract the top result
            result = data[0][0] 
            
            labels.append(f"{sentence} -> {result['label']}")
            score_pct = result['score'] * 100
            scores.append(f"{sentence} -> {score_pct:.2f}%")
        except Exception as e:
            labels.append(f"{sentence} -> Error (Waking up model, try again in 10s)")
            scores.append(f"{sentence} -> 0.00%")
            
    return "\n".join(labels), "\n".join(scores)

# Create the Gradio App
app = gr.Interface(
    fn=analysis_sentimental,
    inputs=gr.Textbox(
        lines=5, 
        placeholder="Enter sentences here (one per line)...", 
        label="Input Text"
    ),
    outputs=[
        gr.Textbox(label="Sentiment Label"), 
        gr.Textbox(label="Confidence Score")
    ],
    title="Sentiment Analysis App",
    examples=[
        ["I am absolutely thrilled with this new update!"],
        ["I'm really frustrated that my delivery is late."],
        ["The food was okay, nothing special.\nHowever, the dessert was fantastic!"]
    ]
)

# Launch the app for Render
if __name__ == "__main__":
    app.launch(server_name="0.0.0.0", server_port=int(os.environ.get('PORT', 7860)))
